### ISSUE TITLE
PagerDuty v1 REST Being Decommissioned On Oct 19 2018

### ISSUE THREAD

**Issue by jbaldo** [danielribeiro/PdClojureBindings#10]
Hello,

Thank you for building closure bindings for the PagerDuty REST API!

Wanted to let you know that the PagerDuty v1 REST API is entering a decommissioning period. On April 24, 2018, we are turning off the ability to generate new v1 API keys. On October 19, 2018 we plan to fully decommission the v1 REST API. [More information here](https://v2.developer.pagerduty.com/v2/docs/v1-rest-api-decommissioning-faq)

Are you interested in migrating to use the v2 of our REST API? Are you currently using these bindings in production?

Let me know if I can answer questions.

Thank you,
John Baldo
Product Manager, PagerDuty Platform

**Comment by danielribeiro** [comment]
Closing this, since I'm archiving this project.
